version: '3.8'

services:
  # Frontend Development Server
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_BASE_URL=http://localhost:8080/api
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - university-network
    stdin_open: true
    tty: true

  # Backend Development (if available)
  backend-dev:
    # Replace with your backend development setup
    image: openjdk:17-jdk-alpine
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DATABASE_URL=jdbc:postgresql://database-dev:5432/university_db_dev
    networks:
      - university-network

  # Development Database
  database-dev:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=university_db_dev
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - university-network

networks:
  university-network:
    driver: bridge

volumes:
  postgres_dev_data:
